// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'features/contacts/data/models/contacts.dart';
import 'features/contacts/data/models/email.dart';
import 'features/contacts/data/models/phone_numbers.dart';
import 'features/contacts/data/models/sim_card.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 314359351187073550),
    name: 'ContactEntity',
    lastPropertyId: const obx_int.IdUid(3, 6424636455379493110),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3334261238287392712),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6000618185744509555),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6424636455379493110),
        name: 'favorite',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'phoneNumbers',
        srcEntity: 'PhoneNumberEntity',
        srcField: 'contact',
      ),
      obx_int.ModelBacklink(
        name: 'emails',
        srcEntity: 'EmailEntity',
        srcField: 'contact',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7103119823991285011),
    name: 'EmailEntity',
    lastPropertyId: const obx_int.IdUid(5, 7452701397111742912),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6479573906234475923),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3607904950604661624),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4426408172445085187),
        name: 'contactId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 7416119173072622725),
        relationField: 'contact',
        relationTarget: 'ContactEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7452701397111742912),
        name: 'labelIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1629779469957198946),
    name: 'PhoneNumberEntity',
    lastPropertyId: const obx_int.IdUid(5, 7680054924153434984),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6800660974171995110),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5905984577387236136),
        name: 'number',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6244324872188539985),
        name: 'contactId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5964977241708805967),
        relationField: 'contact',
        relationTarget: 'ContactEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7680054924153434984),
        name: 'labelIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7755636547005283202),
    name: 'SimCardEntity',
    lastPropertyId: const obx_int.IdUid(4, 6824141360668489478),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6450976262980454121),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7460518238730348187),
        name: 'slot',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7744407962637704240),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6824141360668489478),
        name: 'number',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 7755636547005283202),
    lastIndexId: const obx_int.IdUid(2, 5964977241708805967),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [3238970894615835053, 30633204912583904],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ContactEntity: obx_int.EntityDefinition<ContactEntity>(
      model: _entities[0],
      toOneRelations: (ContactEntity object) => [],
      toManyRelations: (ContactEntity object) => {
        obx_int.RelInfo<PhoneNumberEntity>.toOneBacklink(
          4,
          object.id,
          (PhoneNumberEntity srcObject) => srcObject.contact,
        ): object.phoneNumbers,
        obx_int.RelInfo<EmailEntity>.toOneBacklink(
          4,
          object.id,
          (EmailEntity srcObject) => srcObject.contact,
        ): object.emails,
      },
      getId: (ContactEntity object) => object.id,
      setId: (ContactEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ContactEntity object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addBool(2, object.favorite);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final favoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final object = ContactEntity(name: nameParam, favorite: favoriteParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<ContactEntity>(
          object.phoneNumbers,
          store,
          obx_int.RelInfo<PhoneNumberEntity>.toOneBacklink(
            4,
            object.id,
            (PhoneNumberEntity srcObject) => srcObject.contact,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<ContactEntity>(
          object.emails,
          store,
          obx_int.RelInfo<EmailEntity>.toOneBacklink(
            4,
            object.id,
            (EmailEntity srcObject) => srcObject.contact,
          ),
        );
        return object;
      },
    ),
    EmailEntity: obx_int.EntityDefinition<EmailEntity>(
      model: _entities[1],
      toOneRelations: (EmailEntity object) => [object.contact],
      toManyRelations: (EmailEntity object) => {},
      getId: (EmailEntity object) => object.id,
      setId: (EmailEntity object, int id) {
        object.id = id;
      },
      objectToFB: (EmailEntity object, fb.Builder fbb) {
        final emailOffset = fbb.writeString(object.email);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, emailOffset);
        fbb.addInt64(3, object.contact.targetId);
        fbb.addInt64(4, object.labelIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = EmailEntity(email: emailParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..labelIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );
        object.contact.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.contact.attach(store);
        return object;
      },
    ),
    PhoneNumberEntity: obx_int.EntityDefinition<PhoneNumberEntity>(
      model: _entities[2],
      toOneRelations: (PhoneNumberEntity object) => [object.contact],
      toManyRelations: (PhoneNumberEntity object) => {},
      getId: (PhoneNumberEntity object) => object.id,
      setId: (PhoneNumberEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PhoneNumberEntity object, fb.Builder fbb) {
        final numberOffset = fbb.writeString(object.number);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, numberOffset);
        fbb.addInt64(3, object.contact.targetId);
        fbb.addInt64(4, object.labelIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final numberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = PhoneNumberEntity(number: numberParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..labelIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );
        object.contact.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.contact.attach(store);
        return object;
      },
    ),
    SimCardEntity: obx_int.EntityDefinition<SimCardEntity>(
      model: _entities[3],
      toOneRelations: (SimCardEntity object) => [],
      toManyRelations: (SimCardEntity object) => {},
      getId: (SimCardEntity object) => object.id,
      setId: (SimCardEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SimCardEntity object, fb.Builder fbb) {
        final slotOffset = fbb.writeString(object.slot);
        final nameOffset = fbb.writeString(object.name);
        final numberOffset = fbb.writeString(object.number);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, slotOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, numberOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final slotParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final numberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = SimCardEntity(
          id: idParam,
          slot: slotParam,
          name: nameParam,
          number: numberParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ContactEntity] entity fields to define ObjectBox queries.
class ContactEntity_ {
  /// See [ContactEntity.id].
  static final id = obx.QueryIntegerProperty<ContactEntity>(
    _entities[0].properties[0],
  );

  /// See [ContactEntity.name].
  static final name = obx.QueryStringProperty<ContactEntity>(
    _entities[0].properties[1],
  );

  /// See [ContactEntity.favorite].
  static final favorite = obx.QueryBooleanProperty<ContactEntity>(
    _entities[0].properties[2],
  );

  /// see [ContactEntity.phoneNumbers]
  static final phoneNumbers =
      obx.QueryBacklinkToMany<PhoneNumberEntity, ContactEntity>(
        PhoneNumberEntity_.contact,
      );

  /// see [ContactEntity.emails]
  static final emails = obx.QueryBacklinkToMany<EmailEntity, ContactEntity>(
    EmailEntity_.contact,
  );
}

/// [EmailEntity] entity fields to define ObjectBox queries.
class EmailEntity_ {
  /// See [EmailEntity.id].
  static final id = obx.QueryIntegerProperty<EmailEntity>(
    _entities[1].properties[0],
  );

  /// See [EmailEntity.email].
  static final email = obx.QueryStringProperty<EmailEntity>(
    _entities[1].properties[1],
  );

  /// See [EmailEntity.contact].
  static final contact = obx.QueryRelationToOne<EmailEntity, ContactEntity>(
    _entities[1].properties[2],
  );

  /// See [EmailEntity.labelIndex].
  static final labelIndex = obx.QueryIntegerProperty<EmailEntity>(
    _entities[1].properties[3],
  );
}

/// [PhoneNumberEntity] entity fields to define ObjectBox queries.
class PhoneNumberEntity_ {
  /// See [PhoneNumberEntity.id].
  static final id = obx.QueryIntegerProperty<PhoneNumberEntity>(
    _entities[2].properties[0],
  );

  /// See [PhoneNumberEntity.number].
  static final number = obx.QueryStringProperty<PhoneNumberEntity>(
    _entities[2].properties[1],
  );

  /// See [PhoneNumberEntity.contact].
  static final contact =
      obx.QueryRelationToOne<PhoneNumberEntity, ContactEntity>(
        _entities[2].properties[2],
      );

  /// See [PhoneNumberEntity.labelIndex].
  static final labelIndex = obx.QueryIntegerProperty<PhoneNumberEntity>(
    _entities[2].properties[3],
  );
}

/// [SimCardEntity] entity fields to define ObjectBox queries.
class SimCardEntity_ {
  /// See [SimCardEntity.id].
  static final id = obx.QueryIntegerProperty<SimCardEntity>(
    _entities[3].properties[0],
  );

  /// See [SimCardEntity.slot].
  static final slot = obx.QueryStringProperty<SimCardEntity>(
    _entities[3].properties[1],
  );

  /// See [SimCardEntity.name].
  static final name = obx.QueryStringProperty<SimCardEntity>(
    _entities[3].properties[2],
  );

  /// See [SimCardEntity.number].
  static final number = obx.QueryStringProperty<SimCardEntity>(
    _entities[3].properties[3],
  );
}
